name: Rebuild NixOS

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  rebuild:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=https://nixpkgs.cachix.org
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Install Tailscale
        run: |
          nix profile install nixpkgs#tailscale
          # Add nix profile binaries to PATH
          echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH

      - name: Connect to Tailscale
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_TOKEN }}
        run: |
          # Start tailscaled daemon
          sudo $(which tailscaled) --tun=userspace-networking --socks5-server=localhost:1055 &
          sleep 5  # Give tailscaled time to start
          
          # Connect to Tailscale
          sudo $(which tailscale) up --authkey "$TAILSCALE_AUTHKEY"
          timeout 60s bash -c 'until sudo $(which tailscale) status | grep -q "Connected"; do sleep 2; done'

      - name: Install nixos-rebuild
        run: nix profile install nixpkgs#nixos-rebuild

      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Verify Remote Host Accessibility
        env:
          ETHERNIX: ${{ vars.ETHERNIX }}
        run: |
          timeout 30s bash -c 'until ssh -q aloshy@$ETHERNIX exit; do sleep 2; done'

      - name: Rebuild NixOS
        env:
          ETHERNIX: ${{ vars.ETHERNIX }}
        run: |
          nixos-rebuild switch \
            --flake .#ethernix \
            --target-host "aloshy@$ETHERNIX" \
            --use-remote-sudo \
            --show-trace