name: Rebuild NixOS

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  rebuild:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'

      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:ci

      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Build and Deploy
        env:
          ETHERNIX: ${{ vars.ETHERNIX }}
        run: |
          # First build locally to catch any errors
          nix build .#nixosConfigurations.ethernix.config.system.build.toplevel
          
          # Then deploy if build succeeds
          nixos-rebuild switch \
            --flake .#ethernix \
            --target-host "aloshy@$ETHERNIX" \
            --use-remote-sudo \
            --show-trace